Vrac:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {  }
      numero_contrat: {  }
      etape: {  }
      vendeur_type: {  }  
      vendeur_identifiant: {  }      
      vendeur:        
        type: collection
        definition:
          fields:            
            nom: {  }
            raison_sociale: {  }
            siret: {  }
            cvi: {  }
            num_accise: {   }
            num_tva_intracomm: {    }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            telephone: {  }
            fax: {  }
            email: {   }
      vendeur_tva: {  }
      adresse_stockage:
        type: collection
        definition:
          fields:
            adresse: {  }
            code_postal: {  }
            commune: {  }
      acheteur_type: {  }  
      acheteur_identifiant: {  }      
      acheteur:        
        type: collection
        definition:
          fields:            
            nom: {  }
            raison_sociale: {  }
            siret: {  }
            cvi: {  }
            num_accise: {   }
            num_tva_intracomm: {    }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            telephone: {  }
            fax: {  }
            email: {   }
      acheteur_tva: {  }
      adresse_livraison:
        type: collection
        definition:
          fields:
            adresse: {  }
            code_postal: {  }
            commune: {  }
      mandataire_exist: {  }
      mandatant: 
        type: array_collection
        definition:
          fields:
            '*': {  }
      mandataire_identifiant: {  }     
      mandataire:
        type: collection
        definition:
          fields:
            nom: {  }
            raison_sociale: {  }
            siret: {  }
            carte_pro: {  }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            telephone: {  }
            fax: {  }
            email: {  }
      premiere_mise_en_marche: {  }
      production_otna: {  }
      apport_union: {  }
      cession_interne: {  }
      original: {  }
      type_transaction: {  }
      produit: {  }
      contient_domaine: {  }
      domaine: {  }
      labels:
        type: array_collection
        definition:
          fields:
            '*': {  }
      mentions:
        type: array_collection
        definition:
          fields:
            '*': {  }
      volume_propose: {  }
      annexe: {  }
      prix_unitaire: {  }
      type_prix: {  }
      determination_prix: {  }
      date_limite_retiraison: {  }
      commentaires_conditions: {  }
      part_cvo: {  }
      prix_total: {  }
      conditions_paiement:
        type: array_collection
        definition:
          fields:
            '*': {  }
      type_echeancier_paiement: {  }
      vin_livre: {  }
      date_debut_retiraison: {  }
      calendrier_retiraison: {  }
      retiraisons:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  lot_cuve: {  }
                  date_retiraison: {  }
                  volume_retire: {  }
                  montant_paiement: {  }
      contrat_pluriannuel: {  }
      reference_contrat_pluriannuel: {  }
      delai_paiement: {  }
      echeancier_paiement: {  }
      paiements:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  date: {  }
                  montant: {  }
      clause_reserve_retiraison: {  }
      export: {  }
      lots:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  numero: {  }
                  contenance_cuve: {  }
                  millesime: {  }
                  pourcentage_annee: {  }
                  degre: {  }
                  presence_allergenes: {  }
                  raisin_quantite: {  }
                  jus_quantite: {  }
                  bouteilles_quantite: {  }
                  bouteilles_contenance_volume: {  }
                  bouteilles_contenance_libelle: {  }
                  volume: {  }
                  date_retiraison: {  }
                  commentaires: {  }
                  metayage:
                    type: collection
                    definition:
                      fields:
                        bailleur: {  }
                        volume_ventillation: {  }
      type_contrat: {  }
      prix_variable: {  }
      part_variable: {  }
      cvo_nature: {  }
      cvo_repartition: {  }
      date_stats: {  }
      date_signature: {  }
      volume_enleve: {  }
      valide:
        type: collection
        definition:
          fields:
            date_saisie: {  }
            identifiant: {  }
            statut: { }
      nature_document: {  }
      date_signature_vendeur: {  }
      date_signature_acheteur: {  }
      date_signature_mandataire: {  }
      commentaires: {  }